###
GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/4

###
DELETE http://localhost:3001/api/persons/5
###


###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "new persona",
  "number": "123"
}

###


###
GET http://localhost:3001/345/pers3434ons
